import React, { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { FlatList, Linking, StatusBar, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { ArrowLeft, ExternalLink, Search } from 'lucide-react-native';

import licensesData from '@/data/licenses.json';
import { logger } from '@/lib/logger';
import { toast } from '@/lib/feedback';
import { C, MIN_TOUCH_TARGET } from '@/theme/tokens';
import { Input } from '@/components/ui';


interface LicenseEntry {
  name: string;
  version: string;
  license: string;
  repository: string | null;
  publisher: string | null;
}

// Real data generated by `npm run licenses:generate` (REMEDIATION.md
// §8.20) — see scripts/generate-licenses.js. Not fetched from an API:
// this is a build-time snapshot of the app's own actual dependency tree,
// so there's nothing to load, error on, or find empty at runtime.
const entries = (licensesData as { generatedAt: string; entries: LicenseEntry[] }).entries;
const generatedAt = (licensesData as { generatedAt: string }).generatedAt;

export default function LicensesScreen() {
  const { t } = useTranslation();
  const router = useRouter();
  const [query, setQuery] = useState('');

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return entries;
    return entries.filter((e) => e.name.toLowerCase().includes(q) || e.license.toLowerCase().includes(q));
  }, [query]);

  const openRepo = (url: string) => {
    Linking.openURL(url).catch((e) => {
      logger.warn('[Licenses] Failed to open repository link:', e);
      toast(t('licenses.couldNotOpenLink'), 'error');
    });
  };

  return (
    <SafeAreaView edges={['top', 'left', 'right']} style={styles.container}>
      <StatusBar barStyle="light-content" backgroundColor={C.bg} />

      <View style={styles.header}>
        <TouchableOpacity
          activeOpacity={0.7}
          onPress={() => router.back()}
          style={styles.backBtn}
          accessibilityRole="button"
          accessibilityLabel={t('licenses.goBack')}
        >
          <ArrowLeft size={18} color={C.white} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>{t('licenses.title')}</Text>
        <View style={{ width: MIN_TOUCH_TARGET }} />
      </View>

      <Input
        icon={<Search size={15} color={C.textMuted} />}
        placeholder={t('licenses.searchPlaceholder')}
        value={query}
        onChangeText={setQuery}
        containerStyle={styles.searchWrap}
      />

      <Text style={styles.countText}>
        {t('licenses.packageCount', { count: entries.length, date: new Date(generatedAt).toLocaleDateString() })}
      </Text>

      <FlatList
        data={filtered}
        keyExtractor={(item) => item.name}
        contentContainerStyle={styles.listContent}
        ListEmptyComponent={<Text style={styles.emptyText}>{t('licenses.noResultsFor', { query })}</Text>}
        renderItem={({ item }) => (
          <TouchableOpacity
            style={styles.row}
            activeOpacity={item.repository ? 0.7 : 1}
            disabled={!item.repository}
            onPress={() => item.repository && openRepo(item.repository)}
            accessibilityRole="button"
            accessibilityLabel={item.repository ? t('licenses.openRepository', { name: item.name }) : item.name}
          >
            <View style={{ flex: 1 }}>
              <Text style={styles.rowName}>{item.name}</Text>
              <Text style={styles.rowMeta}>v{item.version} · {item.license}</Text>
            </View>
            {item.repository && <ExternalLink size={14} color={C.textMuted} />}
          </TouchableOpacity>
        )}
      />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderColor: C.border,
  },
  backBtn: {
    width: MIN_TOUCH_TARGET,
    height: MIN_TOUCH_TARGET,
    borderRadius: MIN_TOUCH_TARGET / 2,
    backgroundColor: C.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: C.white,
  },
  searchWrap: {
    marginHorizontal: 16,
    marginTop: 14,
  },
  countText: {
    fontSize: 12,
    color: C.textMuted,
    marginHorizontal: 16,
    marginTop: 10,
    marginBottom: 4,
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 32,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderColor: C.border,
  },
  rowName: {
    fontSize: 13,
    fontWeight: '700',
    color: C.white,
  },
  rowMeta: {
    fontSize: 12,
    color: C.textSec,
    marginTop: 2,
  },
  emptyText: {
    fontSize: 12,
    color: C.textMuted,
    textAlign: 'center',
    marginTop: 32,
  },
});
